### PR TITLE
bump version

### PR DESCRIPTION
**Pull request by sjoeboo**
bump up gem version for new build/push

### CODE REVIEW

**Comment by iNecas** [comment]
ACK :)

**Comment by iNecas** [comment]
I'm a bit puzzled here, I see 0.0.4 version on rubygems https://rubygems.org/gems/smart_proxy_dhcp_infoblox/ from 9th September, but it still contains an old code.

**Comment by sjoeboo** [comment]
yeah, thats totally my bad, I'll push 0.0.5 up in a moment, hadn't rebased like a fool.

**Comment by sjoeboo** [comment]
0.0.5 pushed, sorry about that!

**Comment by iNecas** [comment]
@sjoeboo it's ok now. Thanks, we will proceed with finishing of packaging and installer

**Comment by sjoeboo** [comment]
@iNecas I'm happy to add additional owners on the gem (and the dns one as well) to make this easier/speedier in future releases...?

**Comment by iNecas** [comment]
That would be awesome, dmitri@appliedlogic.ca and necasik@gmail.com are @witlessbird and my email addresses on github.

**Comment by sjoeboo** [comment]
Done and done:

Owner added successfully.
Owners for gem: smart_proxy_dhcp_infoblox
- necasik@gmail.com
- dmitri@appliedlogic.ca
- matthew.a.nicholson@gmail.com

**Pull request merged**
