### PR TITLE
Use GitHub Actions for CI

### PR DESCRIPTION
**Pull request by ekohl**

### CODE REVIEW

**Comment by timdeluxe** [comment]
@ekohl I am very sure you are seeing that by yourself, but can you have a look at the failing test which is related to rubocop?

**Review by timdeluxe — APPROVED** [review]
I guess GHA also include rubocop so i am fine with merging despite failing tests.

**Comment by evgeni** [comment]
> I guess GHA also include rubocop so i am fine with merging despite failing tests.

Yeah, we'll be dropping jenkins-based testing in https://github.com/theforeman/jenkins-jobs/pull/506, so it's just a temporary thing.

GHA runs Rubocop and there it's passing.

**Review by evgeni — APPROVED** [review]

**Comment by evgeni** [comment]
(reconfigured branch protection to look for GHA result, not Jenkins)

**Pull request merged**
