### PR TITLE
Fixes #18300 - removed unused load_ methods

### PR DESCRIPTION
**Pull request by witlessbird**
And fixed failing tests. This is dependent on https://github.com/theforeman/smart-proxy/pull/502.

### CODE REVIEW

**Comment by witlessbird** [comment]
https://github.com/theforeman/smart-proxy/pull/502 has been merged; this PR should be good to merge now too. 

OT: @sjoeboo -- any chance I could get commit access to this repository? We should probably chat re: commit rules before this though?

**Comment by sjoeboo** [comment]
@witlessbird looks good to me. I'm all for giving you commit access...however i don't hold the keys to the repo to actually make it happen.

**Comment by witlessbird** [comment]
@sjoeboo: Oh, my apologies, I thought you were the owner...  @domcleal -- would you know?

**Comment by domcleal** [comment]
@sjoeboo add and manage members here: https://github.com/orgs/theforeman/teams/proxy-infoblox

**Pull request merged**
